### ISSUE TITLE
Possible problem with  SPI_FLASH_FAST_READ_DUAL_OUTPUT driver.

### ISSUE THREAD

**Issue by at91rm9200** [BrunoLevy/learn-fpga#34]
Hello Bruno,

there might be a problem in the SPI_FLASH_FAST_READ_DUAL_OUTPUT driver. If I change line 203 in MappedSPIFlash.v to 

   assign  MOSI_out = sending && cmd_addr[31]; // was 39

then this driver works with my board, which is equipped with a Winbond W25Q32JV Flash.

Regards, Bernd.

**Comment by BrunoLevy** [comment]
You are perfectly right ! Thank you very much
(pushed your fix)
Best regards,
-- Bruno
