### ISSUE TITLE
Errors in UART read

### ISSUE THREAD

**Issue by BrunoLevy** [BrunoLevy/learn-fpga#38]
Sometimes on the ULX3S I get random characters from the UART. 
To reproduce: start FIRMWARE/EXAMPLES/tty_OLED.c
(or use the left arrow in the "commander" GUI to start the shell)

**Comment by BrunoLevy** [comment]
Fixed using BB/IFS1P3BX combo as follows:
(but I'm not 100% sure of what I deed though...)

     wire RXD_btw;
     BB RXD_bb(
       .I(1'b0), 
       .O(RXD_btw), 
       .B(RXD), 
       .T(1'b1)
     );
     IFS1P3BX RXD_pin(
       .SCLK(clk),		    
       .D(RXD_btw),
       .Q(RXD_internal),
       .PD(1'b0)		    
     );

**Comment by Mecrisp** [comment]
https://github.com/jamesbowman/swapforth/issues/45
https://github.com/jamesbowman/swapforth/pull/49
